import type { Metadata } from "next";
import NavBar from "@/components/NavBar/NavBar";
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full`}
    >
      <body className="min-h-screen flex flex-col px-5">
        <NavBar/>
        <main className="flex-1 flex">{children}</main>
      </body>
    </html>
  );
}
